<!doctype html><html lang=en-us><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge,chrome=1"><title>matplotlib backend issue | My New Hugo Site</title><meta name=viewport content="width=device-width,minimum-scale=1"><meta name=description content="using different backends for matplotlib might cause some unexpected issues: today, i am trying to run a program that uses the following function:
plt.figure() figManager = plt.get_current_fig_manager() figManager.window.showMaximized() however, i found when using the backend of Tk, it gives error, saying get_current_fig_manager is not available, so when i switch to qt4egg, everything works well.
how to switch the backend for matplotlib? first find the configure directory for matplotlib on your computer"><meta name=generator content="Hugo 0.98.0"><meta name=robots content="noindex, nofollow"><link rel=stylesheet href=/ananke/css/main.min.css><meta property="og:title" content="matplotlib backend issue"><meta property="og:description" content="using different backends for matplotlib might cause some unexpected issues: today, i am trying to run a program that uses the following function:
plt.figure() figManager = plt.get_current_fig_manager() figManager.window.showMaximized() however, i found when using the backend of Tk, it gives error, saying get_current_fig_manager is not available, so when i switch to qt4egg, everything works well.
how to switch the backend for matplotlib? first find the configure directory for matplotlib on your computer"><meta property="og:type" content="article"><meta property="og:url" content="http://example.org/posts/matplotlib-backend-issue/"><meta property="article:section" content="posts"><meta itemprop=name content="matplotlib backend issue"><meta itemprop=description content="using different backends for matplotlib might cause some unexpected issues: today, i am trying to run a program that uses the following function:
plt.figure() figManager = plt.get_current_fig_manager() figManager.window.showMaximized() however, i found when using the backend of Tk, it gives error, saying get_current_fig_manager is not available, so when i switch to qt4egg, everything works well.
how to switch the backend for matplotlib? first find the configure directory for matplotlib on your computer"><meta itemprop=wordCount content="242"><meta itemprop=keywords content><meta name=twitter:card content="summary"><meta name=twitter:title content="matplotlib backend issue"><meta name=twitter:description content="using different backends for matplotlib might cause some unexpected issues: today, i am trying to run a program that uses the following function:
plt.figure() figManager = plt.get_current_fig_manager() figManager.window.showMaximized() however, i found when using the backend of Tk, it gives error, saying get_current_fig_manager is not available, so when i switch to qt4egg, everything works well.
how to switch the backend for matplotlib? first find the configure directory for matplotlib on your computer"></head><body class="ma0 avenir bg-near-white"><header><div class=bg-black><nav class="pv3 ph3 ph4-ns" role=navigation><div class="flex-l justify-between items-center center"><a href=/ class="f3 fw2 hover-white no-underline white-90 dib">My New Hugo Site</a><div class="flex-l items-center"><div class=ananke-socials></div></div></div></nav></div></header><main class=pb7 role=main><article class="flex-l flex-wrap justify-between mw8 center ph3"><header class="mt4 w-100"><aside class="instapaper_ignoref b helvetica tracked">POSTS</aside><div id=sharing class="mt3 ananke-socials"></div><h1 class="f1 athelas mt3 mb1">matplotlib backend issue</h1></header><div class="nested-copy-line-height lh-copy serif f4 nested-links mid-gray pr4-l w-two-thirds-l"><p>using different backends for matplotlib might cause some unexpected issues:
today, i am trying to run a program that uses the following function:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span>plt<span style=color:#f92672>.</span>figure()
</span></span><span style=display:flex><span>figManager <span style=color:#f92672>=</span> plt<span style=color:#f92672>.</span>get_current_fig_manager()
</span></span><span style=display:flex><span>figManager<span style=color:#f92672>.</span>window<span style=color:#f92672>.</span>showMaximized()
</span></span></code></pre></div><p>however, i found when using the backend of Tk, it gives error, saying get_current_fig_manager is not available, so when i switch to qt4egg, everything works well.</p><p>how to switch the backend for matplotlib? first find the configure directory for matplotlib on your computer</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#f92672>import</span> matplotlib <span style=color:#66d9ef>as</span> plt
</span></span><span style=display:flex><span>plt<span style=color:#f92672>.</span>get_configdir()
</span></span></code></pre></div><p>then find/generate a file named matplotlibrc, add line:</p><pre tabindex=0><code>backend      : qt4agg
</code></pre><p>reference <a href=http://matplotlib.org/users/customizing.html>here</a></p><p>another issue with using qt4 as backend is below from <a href=http://stackoverflow.com/questions/33984798/matplotlib-using-qt4-backend-has-issue-with-cached-renderer>stackoverflow</a>
I was trying to use matplotlib to replot an image in a faster way, so instead of replotting everything, I use set_data method of the AxesImage class as below:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#f92672>import</span> numpy <span style=color:#66d9ef>as</span> np
</span></span><span style=display:flex><span><span style=color:#f92672>import</span> time
</span></span><span style=display:flex><span><span style=color:#f92672>import</span> matplotlib.pyplot <span style=color:#66d9ef>as</span> plt
</span></span><span style=display:flex><span>    
</span></span><span style=display:flex><span>fig, ax <span style=color:#f92672>=</span> plt<span style=color:#f92672>.</span>subplots()
</span></span><span style=display:flex><span>img <span style=color:#f92672>=</span> plt<span style=color:#f92672>.</span>imshow(np<span style=color:#f92672>.</span>random<span style=color:#f92672>.</span>rand(<span style=color:#ae81ff>100</span>, <span style=color:#ae81ff>100</span>))
</span></span><span style=display:flex><span>    
</span></span><span style=display:flex><span>img<span style=color:#f92672>.</span>set_data(np<span style=color:#f92672>.</span>random<span style=color:#f92672>.</span>rand(<span style=color:#ae81ff>100</span>, <span style=color:#ae81ff>100</span>))
</span></span><span style=display:flex><span>ax<span style=color:#f92672>.</span>draw_artist(ax<span style=color:#f92672>.</span>patch)
</span></span><span style=display:flex><span>ax<span style=color:#f92672>.</span>draw_artist(img)
</span></span><span style=display:flex><span>fig<span style=color:#f92672>.</span>canvas<span style=color:#f92672>.</span>update()
</span></span><span style=display:flex><span>fig<span style=color:#f92672>.</span>canvas<span style=color:#f92672>.</span>flush_events()
</span></span></code></pre></div><p>I encountered this error:</p><blockquote><p>Traceback (most recent call last): &mldr;
ax.draw_artist(ax.patch) File &ldquo;/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axes/_base.py&rdquo;,
line 2319, in draw_artist
raise AttributeError(msg) AttributeError: draw_artist can only be used after an initial draw which caches the render</p></blockquote><p>However, if I run the script line by line in python shell (IPython), it works and nothing is wrong. So what is the mystery behind this cached renderer?</p><p>EDIT: add a line <code>fig.canvas.draw()</code> solves the problem, now the remaining question is why running it line by line in IPython shell does not cause the same error?</p><ul class=pa0></ul><div class="mt6 instapaper_ignoref"></div></div><aside class="w-30-l mt6-l"></aside></article></main><footer class="bg-black bottom-0 w-100 pa3" role=contentinfo><div class="flex justify-between"><a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href=http://example.org/>&copy; My New Hugo Site 2022</a><div><div class=ananke-socials></div></div></div></footer></body></html>